import { BASE_URL } from '../seo/meta.js';

export const BLOG_STATES = [
  { slug: 'california', label: 'California' },
  { slug: 'florida', label: 'Florida' },
  { slug: 'texas', label: 'Texas' },
  { slug: 'new-york', label: 'New York', aliases: ['newyork'] },
  { slug: 'illinois', label: 'Illinois' },
  { slug: 'pennsylvania', label: 'Pennsylvania' },
];

export const BLOG_POSTS = [
  {
    type: 'auto',
    state: 'california',
    slug: 'why-auto-claims-denied',
    title: 'Why Auto Insurance Claims Get Denied in California',
    description: 'Common California denial reasons and what to do next.',
    date: '2026-02-17',
    readingTime: '8 min',
    path: '/blog/california/why-auto-claims-denied',
    canonicalUrl: `${BASE_URL}/blog/california/why-auto-claims-denied`,
    internalLinks: [
      `${BASE_URL}/auto-insurance-claims-denied-california`,
      `${BASE_URL}/auto-insurance-claims-denied-california/policy-lapse-or-cancellation`,
      `${BASE_URL}/auto-insurance-claims-denied-california/missed-reporting-deadline`,
    ],
    module: './posts/california/why-auto-claims-denied.js',
  },
  {
    type: 'auto',
    state: 'california',
    slug: 'how-appeal-auto-claim',
    title: 'How to Appeal a Denied Auto Insurance Claim in California',
    description: 'A step-by-step California appeal checklist and evidence guide.',
    date: '2026-02-17',
    readingTime: '10 min',
    path: '/blog/california/how-appeal-auto-claim',
    canonicalUrl: `${BASE_URL}/blog/california/how-appeal-auto-claim`,
    internalLinks: [`${BASE_URL}/auto-insurance-claims-denied-california`, `${BASE_URL}/blog/california/why-auto-claims-denied`],
    module: './posts/california/how-appeal-auto-claim.js',
  },
  {
    type: 'case-auto',
    state: 'california',
    slug: 'case-auto-success',
    title: 'California Auto Claim Appeal Success Story',
    description: 'A real-world case example of overturning an auto claim denial in California.',
    date: '2026-02-17',
    readingTime: '7 min',
    path: '/blog/california/case-auto-success',
    canonicalUrl: `${BASE_URL}/blog/california/case-auto-success`,
    internalLinks: [`${BASE_URL}/blog/california/how-appeal-auto-claim`, `${BASE_URL}/auto-insurance-claims-denied-california`],
    module: './posts/california/case-auto-success.js',
  },
  {
    type: 'health',
    state: 'california',
    slug: 'why-health-claims-denied',
    title: 'Why Health Insurance Claims Get Denied in California',
    description: 'The most common California health denial patterns and next steps.',
    date: '2026-02-17',
    readingTime: '9 min',
    path: '/blog/california/why-health-claims-denied',
    canonicalUrl: `${BASE_URL}/blog/california/why-health-claims-denied`,
    internalLinks: [`${BASE_URL}/health-insurance-claims-denied-california`, `${BASE_URL}/blog/california/how-appeal-health-claim`],
    module: './posts/california/why-health-claims-denied.js',
  },
  {
    type: 'health',
    state: 'california',
    slug: 'how-appeal-health-claim',
    title: 'How to Appeal a Denied Health Insurance Claim in California',
    description: 'How to build a stronger appeal and use California review options.',
    date: '2026-02-17',
    readingTime: '12 min',
    path: '/blog/california/how-appeal-health-claim',
    canonicalUrl: `${BASE_URL}/blog/california/how-appeal-health-claim`,
    internalLinks: [`${BASE_URL}/health-insurance-claims-denied-california`, `${BASE_URL}/blog/california/why-health-claims-denied`],
    module: './posts/california/how-appeal-health-claim.js',
  },
  {
    type: 'case-health',
    state: 'california',
    slug: 'case-health-success',
    title: 'California Health Claim Appeal Success Story',
    description: 'A case example of appealing a California health denial successfully.',
    date: '2026-02-17',
    readingTime: '8 min',
    path: '/blog/california/case-health-success',
    canonicalUrl: `${BASE_URL}/blog/california/case-health-success`,
    internalLinks: [`${BASE_URL}/blog/california/how-appeal-health-claim`, `${BASE_URL}/health-insurance-claims-denied-california`],
    module: './posts/california/case-health-success.js',
  },

  {
    type: 'auto',
    state: 'florida',
    slug: 'why-auto-claims-denied',
    title: 'Why Auto Insurance Claims Get Denied in Florida',
    description: 'Common Florida denial reasons and what to do next.',
    date: '2026-02-17',
    readingTime: '8 min',
    path: '/blog/florida/why-auto-claims-denied',
    canonicalUrl: `${BASE_URL}/blog/florida/why-auto-claims-denied`,
    internalLinks: [`${BASE_URL}/auto-insurance-claims-denied-florida`],
    module: './posts/florida/why-auto-claims-denied.js',
  },
  {
    type: 'auto',
    state: 'florida',
    slug: 'how-appeal-auto-claim',
    title: 'How to Appeal a Denied Auto Insurance Claim in Florida',
    description: 'A step-by-step Florida appeal checklist and evidence guide.',
    date: '2026-02-17',
    readingTime: '10 min',
    path: '/blog/florida/how-appeal-auto-claim',
    canonicalUrl: `${BASE_URL}/blog/florida/how-appeal-auto-claim`,
    internalLinks: [`${BASE_URL}/blog/florida/why-auto-claims-denied`, `${BASE_URL}/auto-insurance-claims-denied-florida`],
    module: './posts/florida/how-appeal-auto-claim.js',
  },
  {
    type: 'case-auto',
    state: 'florida',
    slug: 'case-auto-success',
    title: 'Florida Auto Claim Appeal Success Story',
    description: 'A real-world case example of overturning an auto claim denial in Florida.',
    date: '2026-02-17',
    readingTime: '7 min',
    path: '/blog/florida/case-auto-success',
    canonicalUrl: `${BASE_URL}/blog/florida/case-auto-success`,
    internalLinks: [`${BASE_URL}/blog/florida/how-appeal-auto-claim`, `${BASE_URL}/auto-insurance-claims-denied-florida`],
    module: './posts/florida/case-auto-success.js',
  },
  {
    type: 'health',
    state: 'florida',
    slug: 'why-health-claims-denied',
    title: 'Why Health Insurance Claims Get Denied in Florida',
    description: 'The most common Florida health denial patterns and next steps.',
    date: '2026-02-17',
    readingTime: '9 min',
    path: '/blog/florida/why-health-claims-denied',
    canonicalUrl: `${BASE_URL}/blog/florida/why-health-claims-denied`,
    internalLinks: [`${BASE_URL}/health-insurance-claims-denied-florida`],
    module: './posts/florida/why-health-claims-denied.js',
  },
  {
    type: 'health',
    state: 'florida',
    slug: 'how-appeal-health-claim',
    title: 'How to Appeal a Denied Health Insurance Claim in Florida',
    description: 'How to build a stronger appeal and use Florida review options.',
    date: '2026-02-17',
    readingTime: '12 min',
    path: '/blog/florida/how-appeal-health-claim',
    canonicalUrl: `${BASE_URL}/blog/florida/how-appeal-health-claim`,
    internalLinks: [`${BASE_URL}/blog/florida/why-health-claims-denied`, `${BASE_URL}/health-insurance-claims-denied-florida`],
    module: './posts/florida/how-appeal-health-claim.js',
  },
  {
    type: 'case-health',
    state: 'florida',
    slug: 'case-health-success',
    title: 'Florida Health Claim Appeal Success Story',
    description: 'A case example of appealing a Florida health denial successfully.',
    date: '2026-02-17',
    readingTime: '8 min',
    path: '/blog/florida/case-health-success',
    canonicalUrl: `${BASE_URL}/blog/florida/case-health-success`,
    internalLinks: [`${BASE_URL}/blog/florida/how-appeal-health-claim`, `${BASE_URL}/health-insurance-claims-denied-florida`],
    module: './posts/florida/case-health-success.js',
  },

  {
    type: 'auto',
    state: 'texas',
    slug: 'why-auto-claims-denied',
    title: 'Why Auto Insurance Claims Get Denied in Texas',
    description: 'Common Texas denial reasons and what to do next.',
    date: '2026-02-17',
    readingTime: '8 min',
    path: '/blog/texas/why-auto-claims-denied',
    canonicalUrl: `${BASE_URL}/blog/texas/why-auto-claims-denied`,
    internalLinks: [`${BASE_URL}/auto-insurance-claims-denied-texas`],
    module: './posts/texas/why-auto-claims-denied.js',
  },
  {
    type: 'auto',
    state: 'texas',
    slug: 'how-appeal-auto-claim',
    title: 'How to Appeal a Denied Auto Insurance Claim in Texas',
    description: 'A step-by-step Texas appeal checklist and evidence guide.',
    date: '2026-02-17',
    readingTime: '10 min',
    path: '/blog/texas/how-appeal-auto-claim',
    canonicalUrl: `${BASE_URL}/blog/texas/how-appeal-auto-claim`,
    internalLinks: [`${BASE_URL}/blog/texas/why-auto-claims-denied`, `${BASE_URL}/auto-insurance-claims-denied-texas`],
    module: './posts/texas/how-appeal-auto-claim.js',
  },
  {
    type: 'case-auto',
    state: 'texas',
    slug: 'case-auto-success',
    title: 'Texas Auto Claim Appeal Success Story',
    description: 'A real-world case example of overturning an auto claim denial in Texas.',
    date: '2026-02-17',
    readingTime: '7 min',
    path: '/blog/texas/case-auto-success',
    canonicalUrl: `${BASE_URL}/blog/texas/case-auto-success`,
    internalLinks: [`${BASE_URL}/blog/texas/how-appeal-auto-claim`, `${BASE_URL}/auto-insurance-claims-denied-texas`],
    module: './posts/texas/case-auto-success.js',
  },
  {
    type: 'health',
    state: 'texas',
    slug: 'why-health-claims-denied',
    title: 'Why Health Insurance Claims Get Denied in Texas',
    description: 'The most common Texas health denial patterns and next steps.',
    date: '2026-02-17',
    readingTime: '9 min',
    path: '/blog/texas/why-health-claims-denied',
    canonicalUrl: `${BASE_URL}/blog/texas/why-health-claims-denied`,
    internalLinks: [`${BASE_URL}/health-insurance-claims-denied-texas`],
    module: './posts/texas/why-health-claims-denied.js',
  },
  {
    type: 'health',
    state: 'texas',
    slug: 'how-appeal-health-claim',
    title: 'How to Appeal a Denied Health Insurance Claim in Texas',
    description: 'How to build a stronger appeal and use Texas review options.',
    date: '2026-02-17',
    readingTime: '12 min',
    path: '/blog/texas/how-appeal-health-claim',
    canonicalUrl: `${BASE_URL}/blog/texas/how-appeal-health-claim`,
    internalLinks: [`${BASE_URL}/blog/texas/why-health-claims-denied`, `${BASE_URL}/health-insurance-claims-denied-texas`],
    module: './posts/texas/how-appeal-health-claim.js',
  },
  {
    type: 'case-health',
    state: 'texas',
    slug: 'case-health-success',
    title: 'Texas Health Claim Appeal Success Story',
    description: 'A case example of appealing a Texas health denial successfully.',
    date: '2026-02-17',
    readingTime: '8 min',
    path: '/blog/texas/case-health-success',
    canonicalUrl: `${BASE_URL}/blog/texas/case-health-success`,
    internalLinks: [`${BASE_URL}/blog/texas/how-appeal-health-claim`, `${BASE_URL}/health-insurance-claims-denied-texas`],
    module: './posts/texas/case-health-success.js',
  },

  {
    type: 'auto',
    state: 'new-york',
    slug: 'why-auto-claims-denied',
    title: 'Why Auto Insurance Claims Get Denied in New York',
    description: 'Common New York denial reasons and what to do next.',
    date: '2026-02-17',
    readingTime: '8 min',
    path: '/blog/new-york/why-auto-claims-denied',
    canonicalUrl: `${BASE_URL}/blog/new-york/why-auto-claims-denied`,
    internalLinks: [`${BASE_URL}/auto-insurance-claims-denied-new-york`],
    module: './posts/new-york/why-auto-claims-denied.js',
  },
  {
    type: 'auto',
    state: 'new-york',
    slug: 'how-appeal-auto-claim',
    title: 'How to Appeal a Denied Auto Insurance Claim in New York',
    description: 'A step-by-step New York appeal checklist and evidence guide.',
    date: '2026-02-17',
    readingTime: '10 min',
    path: '/blog/new-york/how-appeal-auto-claim',
    canonicalUrl: `${BASE_URL}/blog/new-york/how-appeal-auto-claim`,
    internalLinks: [`${BASE_URL}/blog/new-york/why-auto-claims-denied`, `${BASE_URL}/auto-insurance-claims-denied-new-york`],
    module: './posts/new-york/how-appeal-auto-claim.js',
  },
  {
    type: 'case-auto',
    state: 'new-york',
    slug: 'case-auto-success',
    title: 'New York Auto Claim Appeal Success Story',
    description: 'A real-world case example of overturning an auto claim denial in New York.',
    date: '2026-02-17',
    readingTime: '7 min',
    path: '/blog/new-york/case-auto-success',
    canonicalUrl: `${BASE_URL}/blog/new-york/case-auto-success`,
    internalLinks: [`${BASE_URL}/blog/new-york/how-appeal-auto-claim`, `${BASE_URL}/auto-insurance-claims-denied-new-york`],
    module: './posts/new-york/case-auto-success.js',
  },
  {
    type: 'health',
    state: 'new-york',
    slug: 'why-health-claims-denied',
    title: 'Why Health Insurance Claims Get Denied in New York',
    description: 'The most common New York health denial patterns and next steps.',
    date: '2026-02-17',
    readingTime: '9 min',
    path: '/blog/new-york/why-health-claims-denied',
    canonicalUrl: `${BASE_URL}/blog/new-york/why-health-claims-denied`,
    internalLinks: [`${BASE_URL}/health-insurance-claims-denied-new-york`],
    module: './posts/new-york/why-health-claims-denied.js',
  },
  {
    type: 'health',
    state: 'new-york',
    slug: 'how-appeal-health-claim',
    title: 'How to Appeal a Denied Health Insurance Claim in New York',
    description: 'How to build a stronger appeal and use New York review options.',
    date: '2026-02-17',
    readingTime: '12 min',
    path: '/blog/new-york/how-appeal-health-claim',
    canonicalUrl: `${BASE_URL}/blog/new-york/how-appeal-health-claim`,
    internalLinks: [`${BASE_URL}/blog/new-york/why-health-claims-denied`, `${BASE_URL}/health-insurance-claims-denied-new-york`],
    module: './posts/new-york/how-appeal-health-claim.js',
  },
  {
    type: 'case-health',
    state: 'new-york',
    slug: 'case-health-success',
    title: 'New York Health Claim Appeal Success Story',
    description: 'A case example of appealing a New York health denial successfully.',
    date: '2026-02-17',
    readingTime: '8 min',
    path: '/blog/new-york/case-health-success',
    canonicalUrl: `${BASE_URL}/blog/new-york/case-health-success`,
    internalLinks: [`${BASE_URL}/blog/new-york/how-appeal-health-claim`, `${BASE_URL}/health-insurance-claims-denied-new-york`],
    module: './posts/new-york/case-health-success.js',
  },

  // Pennsylvania
  {
    type: 'auto',
    state: 'pennsylvania',
    slug: 'why-auto-claims-denied',
    title: 'Why Auto Insurance Claims Get Denied in Pennsylvania',
    description: 'Common Pennsylvania denial reasons and what to do next.',
    date: '2026-02-20',
    readingTime: '8 min',
    path: '/blog/pennsylvania/why-auto-claims-denied',
    canonicalUrl: `${BASE_URL}/blog/pennsylvania/why-auto-claims-denied`,
    internalLinks: [`${BASE_URL}/auto-insurance-claims-denied-pennsylvania`],
    module: './posts/pennsylvania/why-auto-claims-denied.js',
  },
  {
    type: 'auto',
    state: 'pennsylvania',
    slug: 'how-appeal-auto-claim',
    title: 'How to Appeal a Denied Auto Insurance Claim in Pennsylvania',
    description: 'A step-by-step Pennsylvania appeal checklist and evidence guide.',
    date: '2026-02-20',
    readingTime: '10 min',
    path: '/blog/pennsylvania/how-appeal-auto-claim',
    canonicalUrl: `${BASE_URL}/blog/pennsylvania/how-appeal-auto-claim`,
    internalLinks: [`${BASE_URL}/blog/pennsylvania/why-auto-claims-denied`, `${BASE_URL}/auto-insurance-claims-denied-pennsylvania`],
    module: './posts/pennsylvania/how-appeal-auto-claim.js',
  },
  {
    type: 'case-auto',
    state: 'pennsylvania',
    slug: 'case-auto-success',
    title: 'Pennsylvania Auto Claim Appeal Success Story',
    description: 'A real-world case example of overturning an auto claim denial in Pennsylvania.',
    date: '2026-02-20',
    readingTime: '7 min',
    path: '/blog/pennsylvania/case-auto-success',
    canonicalUrl: `${BASE_URL}/blog/pennsylvania/case-auto-success`,
    internalLinks: [`${BASE_URL}/blog/pennsylvania/how-appeal-auto-claim`, `${BASE_URL}/auto-insurance-claims-denied-pennsylvania`],
    module: './posts/pennsylvania/case-auto-success.js',
  },
  {
    type: 'health',
    state: 'pennsylvania',
    slug: 'why-health-claims-denied',
    title: 'Why Health Insurance Claims Get Denied in Pennsylvania',
    description: 'The most common Pennsylvania health denial patterns and next steps.',
    date: '2026-02-20',
    readingTime: '9 min',
    path: '/blog/pennsylvania/why-health-claims-denied',
    canonicalUrl: `${BASE_URL}/blog/pennsylvania/why-health-claims-denied`,
    internalLinks: [`${BASE_URL}/health-insurance-claims-denied-pennsylvania`],
    module: './posts/pennsylvania/why-health-claims-denied.js',
  },
  {
    type: 'health',
    state: 'pennsylvania',
    slug: 'how-appeal-health-claim',
    title: 'How to Appeal a Denied Health Insurance Claim in Pennsylvania',
    description: 'How to build a stronger appeal and use Pennsylvania consumer assistance.',
    date: '2026-02-20',
    readingTime: '12 min',
    path: '/blog/pennsylvania/how-appeal-health-claim',
    canonicalUrl: `${BASE_URL}/blog/pennsylvania/how-appeal-health-claim`,
    internalLinks: [`${BASE_URL}/blog/pennsylvania/why-health-claims-denied`, `${BASE_URL}/health-insurance-claims-denied-pennsylvania`],
    module: './posts/pennsylvania/how-appeal-health-claim.js',
  },
  {
    type: 'case-health',
    state: 'pennsylvania',
    slug: 'case-health-success',
    title: 'Pennsylvania Health Claim Appeal Success Story',
    description: 'A case example of appealing a Pennsylvania health denial successfully.',
    date: '2026-02-20',
    readingTime: '8 min',
    path: '/blog/pennsylvania/case-health-success',
    canonicalUrl: `${BASE_URL}/blog/pennsylvania/case-health-success`,
    internalLinks: [`${BASE_URL}/blog/pennsylvania/how-appeal-health-claim`, `${BASE_URL}/health-insurance-claims-denied-pennsylvania`],
    module: './posts/pennsylvania/case-health-success.js',
  },

  // Illinois
  {
    type: 'auto',
    state: 'illinois',
    slug: 'why-auto-claims-denied',
    title: 'Why Auto Insurance Claims Get Denied in Illinois',
    description: 'Common Illinois denial reasons and what to do next.',
    date: '2026-02-20',
    readingTime: '8 min',
    path: '/blog/illinois/why-auto-claims-denied',
    canonicalUrl: `${BASE_URL}/blog/illinois/why-auto-claims-denied`,
    internalLinks: [`${BASE_URL}/auto-insurance-claims-denied-illinois`],
    module: './posts/illinois/why-auto-claims-denied.js',
  },
  {
    type: 'auto',
    state: 'illinois',
    slug: 'how-appeal-auto-claim',
    title: 'How to Appeal a Denied Auto Insurance Claim in Illinois',
    description: 'A step-by-step Illinois appeal checklist and evidence guide.',
    date: '2026-02-20',
    readingTime: '10 min',
    path: '/blog/illinois/how-appeal-auto-claim',
    canonicalUrl: `${BASE_URL}/blog/illinois/how-appeal-auto-claim`,
    internalLinks: [`${BASE_URL}/blog/illinois/why-auto-claims-denied`, `${BASE_URL}/auto-insurance-claims-denied-illinois`],
    module: './posts/illinois/how-appeal-auto-claim.js',
  },
  {
    type: 'case-auto',
    state: 'illinois',
    slug: 'case-auto-success',
    title: 'Illinois Auto Claim Appeal Success Story',
    description: 'A real-world case example of overturning an auto claim denial in Illinois.',
    date: '2026-02-20',
    readingTime: '7 min',
    path: '/blog/illinois/case-auto-success',
    canonicalUrl: `${BASE_URL}/blog/illinois/case-auto-success`,
    internalLinks: [`${BASE_URL}/blog/illinois/how-appeal-auto-claim`, `${BASE_URL}/auto-insurance-claims-denied-illinois`],
    module: './posts/illinois/case-auto-success.js',
  },
  {
    type: 'health',
    state: 'illinois',
    slug: 'why-health-claims-denied',
    title: 'Why Health Insurance Claims Get Denied in Illinois',
    description: 'The most common Illinois health denial patterns and next steps.',
    date: '2026-02-20',
    readingTime: '9 min',
    path: '/blog/illinois/why-health-claims-denied',
    canonicalUrl: `${BASE_URL}/blog/illinois/why-health-claims-denied`,
    internalLinks: [`${BASE_URL}/health-insurance-claims-denied-illinois`],
    module: './posts/illinois/why-health-claims-denied.js',
  },
  {
    type: 'health',
    state: 'illinois',
    slug: 'how-appeal-health-claim',
    title: 'How to Appeal a Denied Health Insurance Claim in Illinois',
    description: 'How to build a stronger appeal and use Illinois consumer assistance.',
    date: '2026-02-20',
    readingTime: '12 min',
    path: '/blog/illinois/how-appeal-health-claim',
    canonicalUrl: `${BASE_URL}/blog/illinois/how-appeal-health-claim`,
    internalLinks: [`${BASE_URL}/blog/illinois/why-health-claims-denied`, `${BASE_URL}/health-insurance-claims-denied-illinois`],
    module: './posts/illinois/how-appeal-health-claim.js',
  },
  {
    type: 'case-health',
    state: 'illinois',
    slug: 'case-health-success',
    title: 'Illinois Health Claim Appeal Success Story',
    description: 'A case example of appealing an Illinois health denial successfully.',
    date: '2026-02-20',
    readingTime: '8 min',
    path: '/blog/illinois/case-health-success',
    canonicalUrl: `${BASE_URL}/blog/illinois/case-health-success`,
    internalLinks: [`${BASE_URL}/blog/illinois/how-appeal-health-claim`, `${BASE_URL}/health-insurance-claims-denied-illinois`],
    module: './posts/illinois/case-health-success.js',
  },
];

export const normalizeBlogState = (raw) => {
  const s = String(raw || '').toLowerCase();
  for (const st of BLOG_STATES) {
    if (st.slug === s) return st.slug;
    if (Array.isArray(st.aliases) && st.aliases.includes(s)) return st.slug;
  }
  return s;
};

export const getBlogStateLabel = (stateSlug) => {
  const s = normalizeBlogState(stateSlug);
  return BLOG_STATES.find((st) => st.slug === s)?.label || s;
};

export const getBlogPostsByState = (stateSlug) => {
  const s = normalizeBlogState(stateSlug);
  return BLOG_POSTS.filter((p) => p.state === s);
};

export const getBlogPost = ({ state, slug }) => {
  const s = normalizeBlogState(state);
  const sl = String(slug || '').toLowerCase();
  return BLOG_POSTS.find((p) => p.state === s && p.slug === sl) || null;
};
